# Generated by Django 3.1.3 on 2021-06-08 20:23

import cla_customvotes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du vote')),
                ('starts_on', models.DateTimeField(verbose_name="Début de l'élection")),
                ('ends_on', models.DateTimeField(verbose_name="Fin de l'élection")),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=False, verbose_name="Le vote est actif et accessible (dans le respect des dates d'ouverture)")),
            ],
            options={
                'verbose_name': 'Election',
                'ordering': ('-starts_on',),
            },
        ),
        migrations.CreateModel(
            name='VoteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(choices=[('g1', 'G1'), ('g2', 'G2'), ('g3', 'G3'), ('ie1/ie2', 'IE1/IE2'), ('ie3', 'IE3'), ('ie4', 'IE4'), ('ie5', 'IE5')], max_length=10)),
                ('voted_on', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_custom', to=settings.AUTH_USER_MODEL)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='cla_customvotes.election')),
            ],
            options={
                'verbose_name': 'Vote',
                'ordering': ('user__last_name',),
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('photo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, size=[300, 300], upload_to=cla_customvotes.models.FilePath.photo)),
                ('votes', models.IntegerField(default=0)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='cla_customvotes.election')),
            ],
            options={
                'verbose_name': 'Candidat',
            },
        ),
        migrations.CreateModel(
            name='VoteProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.TextField(help_text='Indiqué une personne par ligne', max_length=1000, verbose_name='Identités des procurants')),
                ('voted_on', models.DateTimeField(default=None, editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_custom_proxies', to=settings.AUTH_USER_MODEL)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxies', to='cla_customvotes.election')),
            ],
            options={
                'verbose_name': 'Procuration',
                'unique_together': {('vote', 'user')},
            },
        ),
    ]
