# Generated by Django 3.1.3 on 2021-02-25 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_on', models.DateTimeField(verbose_name="Début de l'élection")),
                ('ends_on', models.DateTimeField(verbose_name="Fin de l'élection")),
            ],
            options={
                'verbose_name': 'Election',
                'ordering': ('-starts_on',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('email_sent_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Etudiant',
            },
        ),
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_on', models.DateTimeField(auto_now=True)),
                ('content', models.JSONField()),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='cla_enscl.election')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='cla_enscl.user')),
            ],
        ),
    ]
