# Generated by Django 3.1.3 on 2021-02-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfos',
            name='cursus',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
