# Generated by Django 3.1.3 on 2021-10-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_ca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='anticipated',
            field=models.BooleanField(default=False, verbose_name='Election anticipée'),
        ),
    ]
