# Generated by Django 3.1.3 on 2022-02-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_ca', '0002_election_anticipated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='college',
            field=models.CharField(choices=[('g1', 'G1'), ('g2', 'G2'), ('g3', 'G3'), ('ie1/ie2', 'IE1/IE2'), ('ie3', 'IE3'), ('ie4', 'IE4'), ('ie5', 'IE5'), ('ENSCL', 'ENSCL')], max_length=10, verbose_name='Collège électoral'),
        ),
        migrations.AlterField(
            model_name='voteuser',
            name='college',
            field=models.CharField(choices=[('g1', 'G1'), ('g2', 'G2'), ('g3', 'G3'), ('ie1/ie2', 'IE1/IE2'), ('ie3', 'IE3'), ('ie4', 'IE4'), ('ie5', 'IE5'), ('ENSCL', 'ENSCL')], max_length=10),
        ),
    ]
