# Generated by Django 3.1.3 on 2024-03-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_ca', '0003_auto_20220223_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='college',
            field=models.CharField(choices=[('g1', 'G1'), ('g2', 'G2'), ('g3', 'G3'), ('ie1', 'Ie1'), ('ie2', 'Ie2'), ('ie3/ie4/ie5', 'IE3/IE4/IE5'), ('ch1', 'CH1'), ('ch2', 'CH2'), ('ENSCL', 'ENSCL'), ('ie1/ie2', 'IE1/IE2'), ('ie3', 'IE3'), ('ie4', 'IE4'), ('ie5', 'IE5')], max_length=16, verbose_name='Collège électoral'),
        ),
        migrations.AlterField(
            model_name='voteuser',
            name='college',
            field=models.CharField(choices=[('g1', 'G1'), ('g2', 'G2'), ('g3', 'G3'), ('ie1', 'Ie1'), ('ie2', 'Ie2'), ('ie3/ie4/ie5', 'IE3/IE4/IE5'), ('ch1', 'CH1'), ('ch2', 'CH2'), ('ENSCL', 'ENSCL'), ('ie1/ie2', 'IE1/IE2'), ('ie3', 'IE3'), ('ie4', 'IE4'), ('ie5', 'IE5')], max_length=16),
        ),
    ]
