# Generated by Django 3.1.3 on 2026-02-19 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cla_ca', '0004_auto_20240305_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='vote_mode',
            field=models.CharField(choices=[('simple', 'Vote classique (2 voix)'), ('condorcet', 'Vote Condorcet (Schulze)')], default='simple', max_length=16, verbose_name='Mode de vote'),
        ),
        migrations.CreateModel(
            name='CondorcetBallot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(choices=[('g1', 'G1'), ('g2', 'G2'), ('g3', 'G3'), ('ie1', 'Ie1'), ('ie2', 'Ie2'), ('ie3/ie4/ie5', 'IE3/IE4/IE5'), ('ch1', 'CH1'), ('ch2', 'CH2'), ('ENSCL', 'ENSCL'), ('ie1/ie2', 'IE1/IE2'), ('ie3', 'IE3'), ('ie4', 'IE4'), ('ie5', 'IE5')], max_length=16)),
                ('ranked_candidates', models.JSONField()),
                ('voted_on', models.DateTimeField(auto_now=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condorcet_ballots', to='cla_ca.election')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condorcet_ballots_ca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulletin Condorcet',
                'unique_together': {('election', 'user')},
            },
        ),
    ]
