# Generated by Django 3.1.3 on 2021-02-03 00:21

import cla_bdx.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_on', models.DateTimeField()),
                ('ends_on', models.DateTimeField()),
                ('type', models.CharField(choices=[('bda', 'BDA'), ('bde', 'BDE'), ('bdi', 'BDI'), ('bds', 'BDS')], max_length=3, verbose_name='Campagne')),
            ],
            options={
                'verbose_name': 'Campagne',
                'ordering': ('-starts_on',),
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_on', models.DateTimeField()),
                ('ends_on', models.DateTimeField()),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='cla_bdx.campaign')),
            ],
            options={
                'verbose_name': 'Vote',
            },
        ),
        migrations.CreateModel(
            name='VoteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='cla_bdx.vote')),
            ],
            options={
                'verbose_name': 'Vote Campagne BDX',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=90, size=[500, 500], upload_to=cla_bdx.models.FilePath.logo)),
                ('program', models.FileField(blank=True, null=True, upload_to=cla_bdx.models.FilePath.program)),
                ('votes_binary', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='cla_bdx.campaign')),
            ],
            options={
                'verbose_name': 'Liste',
            },
        ),
    ]
