# Generated by Django 3.1.3 on 2021-02-07 14:11

import cla_bdx.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cla_bdx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='display_result_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication des résultats'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voteuser',
            name='voted_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='ends_on',
            field=models.DateTimeField(verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='starts_on',
            field=models.DateTimeField(verbose_name='Début'),
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='list',
            name='program',
            field=models.FileField(blank=True, null=True, upload_to=cla_bdx.models.FilePath.program, verbose_name='Programme'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='ends_on',
            field=models.DateTimeField(verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='starts_on',
            field=models.DateTimeField(verbose_name='Début'),
        ),
    ]
