# Generated by Django 3.1.3 on 2021-02-07 22:47

import cla_bdx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_bdx', '0002_auto_20210207_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignRegulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_on', models.DateField(verbose_name='Voté le')),
                ('file', models.FileField(blank=True, null=True, upload_to=cla_bdx.models.FilePath.regulation, verbose_name='Fichier PDF')),
            ],
            options={
                'verbose_name': 'Règlement des campagnes',
            },
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ('name',), 'verbose_name': 'Liste'},
        ),
    ]
