# Generated by Django 3.1.3 on 2021-04-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_bdx', '0003_auto_20210207_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='penality',
            field=models.FloatField(default=0, verbose_name='Pourcentage de voix de pénalité'),
        ),
    ]
