# Generated by Django 3.1.3 on 2023-12-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_bdx', '0004_list_penality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='type',
            field=models.CharField(choices=[('bda', 'BDA'), ('bde', 'BDE'), ('bdi', 'BDI'), ('bds', 'BDS'), ('bda_enscl', 'BDA ENSCL'), ('bde_enscl', 'BDE ENSCL')], max_length=16, verbose_name='Campagne'),
        ),
    ]
